modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/GlodBlock/AE2FluidCraft-Rework/issues"
displayURL="https://github.com/GlodBlock/AE2FluidCraft-Rework"
logoFile="logo.png"
authors="GlodBlock"
license="LGPL-3.0"

[[mods]]
modId="ae2fc"
version="1.0.0-a"
displayName="Fluid Craft for AE2"
description="Lets you do Crafting... with Fluids!"

[[dependencies.ae2fc]]
modId="forge"
mandatory=true
versionRange="[36.1.10,37.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2fc]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17.0)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2fc]]
modId="jei"
mandatory=false
versionRange="[7.7.0.98,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.ae2fc]]
modId="roughlyenoughitems"
mandatory=false
versionRange="[6.5.436,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.ae2fc]]
modId="appliedenergistics2"
mandatory=true
versionRange="[8.4.7,)"
ordering="AFTER"
side="BOTH"